// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZ4CVv9o4qVnHMRk0S9s0sVHHtEtvRzE',
    appId: '1:758529087410:web:cdeba31c35dcf21672b6ab',
    messagingSenderId: '758529087410',
    projectId: 'chat-app-v01-e4f1d',
    authDomain: 'chat-app-v01-e4f1d.firebaseapp.com',
    storageBucket: 'chat-app-v01-e4f1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9mYRMDt2zyn8nU13o_26bNL7olwCw_E',
    appId: '1:758529087410:android:455c464d371263ec72b6ab',
    messagingSenderId: '758529087410',
    projectId: 'chat-app-v01-e4f1d',
    storageBucket: 'chat-app-v01-e4f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-U0ZKZflnjjDhebzFkGWv_UQEifGitk',
    appId: '1:758529087410:ios:e18bb265cd20d6b872b6ab',
    messagingSenderId: '758529087410',
    projectId: 'chat-app-v01-e4f1d',
    storageBucket: 'chat-app-v01-e4f1d.appspot.com',
    iosBundleId: 'com.example.chatAppV01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-U0ZKZflnjjDhebzFkGWv_UQEifGitk',
    appId: '1:758529087410:ios:8c810534799816d872b6ab',
    messagingSenderId: '758529087410',
    projectId: 'chat-app-v01-e4f1d',
    storageBucket: 'chat-app-v01-e4f1d.appspot.com',
    iosBundleId: 'com.example.chatAppV01.RunnerTests',
  );
}
